### ISSUE TITLE
Plex watchlist issues

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [I-am-PUID-0/DMB#58]
After getting the latest riven updates today, riven no longer reads the plex watchlist. I have not changed anything on my end, it just doesn't scrape anything added to the plex watchlist. I restarted all the containers,  i restarted my pc, i disabled and reenabled plex watchlist, re-authenticated plex with a new token but the issue persists. 

Adding items via the riven front end still works and plex refresh is still triggered after the successful download. Just not using the plex watchlist.

**Comment by Bayharbourbutcher1** [comment]
> Can you provide your logs? 

Sure, here you go! https://www.file.io/6QW5/download/gS96iKmD3NYs

**Comment by Bayharbourbutcher1** [comment]
Here you go, with debug logging
 https://www.file.io/eE3p/download/zPSrAAyrLJMc

**Comment by Bayharbourbutcher1** [comment]
Sure, thanks

**Comment by KodeStar** [comment]
Did that discussion come to any conclusions?

**Comment by Bayharbourbutcher1** [comment]
Unfortunately not, still having the same issue. The issue also persists on a standalone build of riven.

**Comment by KodeStar** [comment]
Apparently it's a known issue with Riven that has been fixed, just waiting for it to be approved and released.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/e43dafb5-9b3c-45a9-af91-077893828b1d">

**Comment by KodeStar** [comment]
https://github.com/rivenmedia/riven/compare/bugfix/plex-watchlist this one I believe, so you could technically run RIVEN_BRANCH=bugfix/plex-watchlist if you really needed it and can't wait

**Comment by Bayharbourbutcher1** [comment]
Thank you. I do have overseerr working right now so, happy to wait. Nothing beats the experience of browsing plex on tv and watchlisting content.

**Comment by KodeStar** [comment]
I haven't managed to get overseer working yet, I get:
```
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: SvelteKitError: POST method not allowed. No actions exist for this page
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: at handle_action_json_request (file:///riven/frontend/build/server/index.js:721:30)
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: at render_page (file:///riven/frontend/build/server/index.js:2351:12)
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: at async resolve2 (file:///riven/frontend/build/server/index.js:3461:24) {
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: status: 405,
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: text: 'Method Not Allowed'
Oct 11, 2024 18:39:26 - INFO - riven_frontend subprocess: }
```
