### ISSUE TITLE
Does not correctly handle deleted files in new Riven releases

### ISSUE THREAD

**Issue by nirmalspeed** [I-am-PUID-0/DMB#60]
**Describe the bug**

Riven was updated and removes some files/dependencies but DMB still has those now-deleted files which are causing issues. 
Ex: `src/routes/library/+page.server.ts` was deleted: 
https://github.com/rivenmedia/riven-frontend/compare/v0.13.1...v0.14.1

**To Reproduce**

Steps to reproduce the behavior.
Install Riven 0.13.1 then update to 0.14.1. The 

**Expected behavior**

DMB should `rm -rf` the old `frontend` folder when there's a new version and rebuild cleanly

**Screenshots**

```
Oct 18, 2024 13:54:33 - INFO - Setting up riven_frontend
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: [vite]: Rollup failed to resolve import "fuse.js" from "/riven/frontend/src/routes/library/+page.server.ts".
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at viteWarn (file:///riven/frontend/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65578:17)
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at onRollupWarning (file:///riven/frontend/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65610:5)
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at onwarn (file:///riven/frontend/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.6/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65273:7)
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at file:///riven/frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19393:13
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at Object.logger [as onLog] (file:///riven/frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:21119:9)
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at ModuleLoader.handleInvalidResolvedId (file:///riven/frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20008:26)
Oct 18, 2024 13:54:41 - INFO - node_build subprocess: at file:///riven/frontend/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19966:26
Oct 18, 2024 13:54:42 - INFO - Stopping riven_frontend

```

**Please complete the following information:**
 - OS: Unraid
 - Supporting Applications: Docker

**Additional context**

**Comment by nirmalspeed** [comment]
So I was able to get around this by entering the docker shell `docker exec -it DMB /bin/sh`,  and deleting the `/riven/frontend/src` folder and changing the versions.txt to be lower than it actually was which triggered DMB to fix things. 

I did play around with a few different things while trying to fix without downgrading, but I believe this should be all that's needed
